### ISSUE TITLE
Testing CTR on Linux

### ISSUE THREAD

**Issue by nonunknown** [BluestormDNA/ProjectPSX#14]
Im using SCPH1001 and Crash Team Racing SCUS-94426 under Ubuntu 20.04

-this is related to DarkLotus's basic linux support's PR

*Edit: I was thinking instead of using WindowsForms in my fork of this project, runs it directly inside godot, to this I just need to know from you @BluestormDNA how the screen is rendered inside winforms, it like a sequence of images? there is a file which I can look how its done?

About CTR, it stucks on Sony Computer Presents (CTR's First Screen) I remember this happing on old versions of ePSXe and it was fully related to the Sound Plugin:
```
setup file    : cdrom:SYSTEM.CNF;1
TCB	00000004
EVENT	00000016
STACK	801ffff0
BOOT =	cdrom:\SCUS_944.26;1
argument =	
KERNEL SETUP!

Configuration : EvCB	0x16		TCB	0x04
boot file     : cdrom:\SCUS_944.26;1
EXEC:PC0(8007793c)  T_ADDR(80010000)  T_SIZE(0007d800)
boot address  : 8007793c 801ffff0
Execute !

                S_ADDR(801ffff0)  S_SIZE()
addr=8008c6fc
ResetGraph:jtb=8008ad38,env=8008ad80

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x55d0cbe367f0 - /usr/bin/cli : (null)
	0x55d0cbde31a9 - /usr/bin/cli : (null)
	0x55d0cbe35a07 - /usr/bin/cli : (null)
	0x7f78200353c0 - /lib/x86_64-linux-gnu/libpthread.so.0 : (null)
	0x7f781fb06859 - /lib/x86_64-linux-gnu/libc.so.6 : abort
	0x55d0cc095835 - /usr/bin/cli : (null)
	0x55d0cc0b326e - /usr/bin/cli : (null)
	0x55d0cc0b36b7 - /usr/bin/cli : monoeg_g_logv
	0x55d0cc0b3773 - /usr/bin/cli : monoeg_g_log
	0x55d0cc0a8c34 - /usr/bin/cli : (null)
	0x55d0cbfd6f7b - /usr/bin/cli : (null)
	0x55d0cbfd963c - /usr/bin/cli : (null)
	0x40b0e686 - Unknown

=================================================================
	Telemetry Dumper:
mono_coop_mutex_lock Cannot transition thread 0x7f781fade780 from STATE_BLOCKING with DO_BLOCKING

```

**Comment by BluestormDNA** [comment]
CTR needs specific SPU features. It's not gonna work as we don't even have a SPU yet.

If you are on DarkLotus, the GPU writted to VRAM wich was just an int array wrapped inside a GDI+ Bitmap to just put it as a background on the panel containing the winform. When the vsync triggered I just invalidated the form and the image was refreshed...

At the moment you should be able to implement your own frontend as long as you implement the IHostWindow interface of ProjectPSX. Thought I'm still in the middle of splitting and refactoring things. I'm doing some test right now and I just pushed a90ff95 wich haves a barebones OpenTK frontend that (maybe?) should run on linux...

**Comment by nonunknown** [comment]
Hey Thanks for response, Abou the SPU thing, I remember disabling it makes games run without problem (there is a way to disable?) , another solution was using SaveStates (I think its not implemented yet, so I can use a savestate from another emulator and use it to go directly to menu) I'm in touch with CTR modding guys, they are making CTR Online too, I wish to use your project so I can make a way to play online without any non-user-friendly stuff.

**Comment by BluestormDNA** [comment]
Well it can't be as disabled as no SPU... Even thought i allow reads and writess to the SPU address space. Savestates are not even considered yet. A lot still to do (like the SPU doh!).
Have you checked if you can run the OpenTK frontend of the last commit on linux?
My linux vm doesn't support openGL so i can't be sure if it works...

**Comment by nonunknown** [comment]
I'll test here, and give a feedback.

**Comment by nonunknown** [comment]
I'm getting this error at Debug and Releases build:

![Screenshot from 2020-06-22 18-09-25](https://user-images.githubusercontent.com/58845030/85335572-9a5aa980-b4b3-11ea-959e-26c300cb51eb.png)
![Screenshot from 2020-06-22 18-09-11](https://user-images.githubusercontent.com/58845030/85335580-9b8bd680-b4b3-11ea-890c-ac1527a79d04.png)

Just for your information, the mentioned file by the console is located at 2 folders:

The main one (screenshot above)
runtimes/linux-x64/native

PS: Since you have changed to .NetCore and godot uses mono, using later than .NetF4.7 makes imposible for me to make it run inside the engine :(

**Comment by BluestormDNA** [comment]
Yeah for some reason OpenTK4 pre 9.1 packs the dependencies on multiple folders and then still fails to provide the correct ones anyway just:
`sudo apt-get install libglfw3` you will probably need too OpenAL for audio so:
`sudo apt-get install libopenal-dev` let me know if it runs

**Comment by nonunknown** [comment]
After installation got this error: 

![Screenshot from 2020-06-22 19-21-08](https://user-images.githubusercontent.com/58845030/85341011-9a5fa700-b4bd-11ea-8745-ae4eae32ed15.png)

**Comment by BluestormDNA** [comment]
Thanks for the log! Do you happen to be on a virtual machine by any chance?

About te .NetCore vs .Net Framework 4.7 should'nt be hard to tune the project a bit to make it work...

**Comment by nonunknown** [comment]
Nope, I'm running on a ubuntu 20.04 notebook, intel graphics 3000HD 

Well, to make it run under godot engine, I just had to make some adjustments on the CDROM, lets see how it goes when your refact is done...

**Comment by BluestormDNA** [comment]
Thanks for testing.
There's a little issue on opentk right now not allowing OpenGL context below 3.3 so that might be it. Anyway will wait till they go out of beta.
I've started to work on the Spu.
Even though not sure when it will be ready I will try to reach you if I get CTR to work. 
Meanwhile closing this.
