### ISSUE TITLE
Thought I should tell you

### ISSUE THREAD

**Issue by tcaudilllg** [BluestormDNA/ProjectPSX#15]
I'm forking your emulator with intent to fortify it into a debugger/resource extractor/translation aid.

If you prefer we could cooperate instead of me just going my own way with your older source (I'm starting from when you got FF7 working). What say you?

**Comment by BluestormDNA** [comment]
Hello there!

I already have enough work handling the Spu. Not sure exactly what the scope on your work is but I suppose you can always PR if you are willing to...

Any reason to choose an old codebase? FF7 was one of the first games to boot (even without mdec and broken dmas)

**Comment by tcaudilllg** [comment]
I like to start at older code bases to get a sense of a project's skeleton. The fundamentals are always in place first. I'm also curious about what games rely on what. It's easier to break something apart when you see it getting put together... something unique that Github offers.

I recommend looking at Neil Corlett's code regarding the SPU. His Highly Experimental plugins are emulators of it.

**Comment by BluestormDNA** [comment]
I see. I will be closing this. If you want to chat about your or this project you can reach me at the emudev discord server https://discord.gg/dkmJAes
