### ISSUE TITLE
More tests on linux

### ISSUE THREAD

**Issue by nonunknown** [BluestormDNA/ProjectPSX#16]
**Os:**
ubuntu 20.04

**.Net:**
Core 3.1

**Error message:**
![Screenshot from 2020-07-06 14-50-51](https://user-images.githubusercontent.com/58845030/86623609-3eeee800-bf98-11ea-8fcb-2ed5dbe1d35d.png)

**Description:**
Well I've made some manual commenting on `Window.cs` class seems to be related with Implementation of `IHostWindow`  when its removed the program runs (of curse without any screen or window) but give no errors...

**Toughts:**

Maybe can be a problem with _OpenTK_ itself due to :  `Failed to create context: GLXBadFBConfig`
or
Render Method from `IHostWindow`:
```
public void Render(int[] vram) {
            vSyncCounter++;
            displayBuffer = vram;
        }
```

**Comment by BluestormDNA** [comment]
Yeah, the latest opentk pre release dosn't support opengl contexts below 3.3
But the opentk frontend (even if very barebones) can run if you happen to have a video card that supports >3.2

![imagen](https://user-images.githubusercontent.com/28767885/87340878-f9f32480-c548-11ea-940b-38f52db95453.png)

Not sure if they will fix it or not. Somewhere i read that GLFW didn't support it...

**Comment by nonunknown** [comment]
Hmm I didnt realized that could be something related to that, I'll try to port it to another frontend, this would in theory solve the problem?

**Comment by BluestormDNA** [comment]
Yep, you already runned ProjectPSX headless.
You can probably use wathever for a frontend as long as you implement the IHostWindow interface.
Bonus for you if you PR a Blazor Web Assembly one ;D

**Comment by nonunknown** [comment]
HAHA I will try with godot, cuz I need it for onlineCTR in linux

**Comment by BluestormDNA** [comment]
Hello There,
I told you on https://github.com/BluestormDNA/ProjectPSX/issues/14#issuecomment-651792251 that i would reach you if got CTR working.
I added capture buffers as of https://github.com/BluestormDNA/ProjectPSX/commit/47b6d472d0f76bb4fd9c580a58aa3c2f00399de6 so now it goes ingame.
It haves some broken geometry but is somewhat playable.

**Comment by nonunknown** [comment]
Nice dude, also in order to port it to run INSIDE the godot engine window, I need to know how to start the emulator and only get the VRAM, run inside a Texture... this means not using the IHostWindow

**Comment by BluestormDNA** [comment]
Not quite sure what you mean.
You can implement the whole IHostWindow interface and only write an actual method for the update vram one. If not you will need to dive into the GPU and get a reference to the VRAM there

**Comment by nonunknown** [comment]
Hmm I'll take a look into this!! thanks for your time
