### ISSUE TITLE
Compatibility with NetStandard2.0 and NetFramework

### ISSUE THREAD

**Issue by EntityFX** [BluestormDNA/ProjectPSX#17]
Hello,

Is there any plans to have compatibility with NetStandard2.0 to be playable on mono/net framework?

Also is it possible to have this cross platform? F.e. it is possible to use Avalonia host to be launched on Linux.

**Comment by BluestormDNA** [comment]
Hello There!

I have no plans on going back from NetCore 3.1 on the contrary my plans go to Net5. Anyway if you need it you can probably backport to NetFramework without much problem. There's a stalled NetFramework branch in the repo: https://github.com/BluestormDNA/ProjectPSX/tree/NetFramework48

ProjectPSX is already cross platform. Look here: https://github.com/BluestormDNA/ProjectPSX/issues/14#issuecomment-647779702 and here: https://github.com/BluestormDNA/ProjectPSX/issues/16#issuecomment-657726714The OpenTK host runs on Linux. It's a test on crossplatform so it haves a very basic UI with just an OpenTK (glfw3) window to draw the full VRAM, input for gamepad, and sound. To make it run once the window has appeared just DRAG AND DROP your cue/bin file.

Technically you can build an Avalonia project just implement the ProjectPSX IHostWindow interface to let it know how/where to draw, and just call ProjectPSX RunFrame() 60 times a second...
