### ISSUE TITLE
How to make like tv output, not vram renderer.

### ISSUE THREAD

**Issue by dimutch833** [BluestormDNA/ProjectPSX#2]
Pls help

**Comment by BluestormDNA** [comment]
As the faq says: _The emulator is very early on development **there is no real tv output "screen".** What you see rendered is the Playstation whole VRAM._
At the moment the VRAM viewer is handy to debug emulation.
Handling that would mean to put effort on the UI (something that at the moment is practically non existant) and its gonna be scraped sooner or later to get rid of winforms.
Also, there are a lot of more important things to handle right now (like broken CDROM timmings) than a screen.

EDIT: Screen output was added on later commit: https://github.com/BluestormDNA/ProjectPSX/commit/027de71e2716a54aa354bfabe429784b8eb29c14
 Use Tab Key to toggle VRAM viewer on/off.

**Comment by dimutch833** [comment]
why so laggy

**Comment by BluestormDNA** [comment]
I dont know what you are trying.
What are you loading? What are your specs? What Speed or fps are shown on the titlebar?

**Comment by dimutch833** [comment]
crash bandicoot  gt 1030 8gb ram  core i3 4130 speed 30% fps 5

**Comment by BluestormDNA** [comment]
Keep in mind that as a WIP project this is not very optimized. Thought i plan on doing some work there soon. If you are just looking for a playstation emulator there are more capable ones out there.

Anyway, try to compile the latest version on release.
I have a slower CPU than yours and can get some more:

![Captura](https://user-images.githubusercontent.com/28767885/63612882-a8177800-c5df-11e9-9f51-00be69a50711.PNG)

If you want to try more things you can get some more underclocking the emulated cpu by rising the bus.tick value from 200 to 300 or 400 (it can break games) on the ProjectPSX.cs class

I can reach almost 100 fps on 400 (wich means emulated cpu underclocked to 25%) it works on crash bandicoot thought it can break other games...
